# ── 摄像头配置文件 ──
cam0:
  camera_model: pinhole
  intrinsics: [1653.275628, 1654.027585, 648.592971, 355.735559]  # fx, fy, cx, cy
  distortion_model: radtan                                       # radtan = 5个畸变系数
  distortion_coeffs: [0.302917, -1.821095, -0.002170, -0.000488, 3.623027]
  resolution: [1280, 720]
  image_topic: camera/image_raw
  tag_topic: /detector/tags
  rig_body: rig
